#!/bin/bash
while [ 1 -eq 1 ]
do
echo "1.Запустить редактор nano"
echo "2.Запустить редактор vi"
echo "3.Запустить браузер links"
echo "4.Выйти в меню"
read command
if [[ $command == "1" ]]
then eval nano
fi
if [[ $command == "2" ]]
then eval vi
fi
if [[ $command == "3" ]]
then eval links
fi
if [[ $command == "4" ]]
then exit 0
fi
done