#!/bin/bash

HOM="/home/user"
BackupDate=$(ls $HOM | grep -E "^Backup-" | sort -n | tail -1 | sed 's/^Backup-//')
Backup="$HOM/Backup-${BackupDate}"

if [[ -z "$BackupDate" ]]
then echo "Backup not found"
exit 1
fi
if [[ ! -d $HOM/restore ]]
then mkdir $HOM/restore
else
rm -r $HOM/restore
mkdir $HOM/restore
fi
for File in $(ls $Backup | grep -Ev "\.[0-9]{4}-[0-9]{2}-[0-9]{2}$");
do
cp "${Backup}/${File}" "$HOM/restore/${File}"
done