#!/bin/bash
previous_ppid=-1
sum=0
cnt=0
while read line
do
ppid=$(echo $line | cut -d ":" -f 2 | grep -E -s -o "[0-9]+")
sleepavg=$(echo $line | cut -d ":" -f 3 | grep -E -s -o "[0-9]+")
if [[ $previous_ppid != -1 && $ppid != $previous_ppid ]]
then echo Average_Running_Children_of_ParentID=$previous_ppid is $(echo "$sum / $cnt" | bc -l) >> tmp2
sum=0
cnt=0
fi
sum=$(echo "$sum + $sleepavg" | bc -l)
previous_ppid=$ppid
let cnt=$cnt+1
echo $line >> tmp2
done < ans4
echo Average_Running_Children_of_ParentID=$previous_ppid is $(echo "$sum / $cnt" | bc -l) >> tmp2
