#!/bin/bash
echo $$ > mypid
i=1
operation="+"
sigterm()
{
echo "STOP"
exit 0
}

user1()
{
operation="+"
}

user2()
{
operation="*"
}

trap 'sigterm' SIGTERM
trap 'user1' USR1
trap 'user2' USR2
while true
do
if [[ $operation == "+" ]]
then let i=$i+2
fi
if [[ $operation == "*" ]]
then let i=$i*2
fi
echo $i
sleep 1
done