#!/bin/bash

while true
do
read line
if [[ $line == "TERM" ]]
then kill -SIGTERM $(cat mypid)
exit 0
fi
if [[ $line == "+" ]]
then kill -USR1 $(cat mypid)
fi
if [[ $line == "*" ]]
then kill -USR2 $(cat mypid)
fi
done